# Generated by Django 4.0.2 on 2022-04-14 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='location',
            new_name='college_name',
        ),
    ]
