# Generated by Django 4.0.2 on 2022-04-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='comp_name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_desc',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='Jsalary',
            field=models.IntegerField(),
        ),
    ]
