# Generated by Django 4.0.2 on 2022-04-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_resume_comp_name_resume_job_desc_alter_job_jsalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='comp_name',
            field=models.CharField(default='Any', max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_desc',
            field=models.CharField(default='Any', max_length=100),
        ),
    ]
